# Generated by Django 4.1.1 on 2022-10-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0002_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[('en_cours', 'en_cours'), ('en_ligne', 'En ligne'), ('cancelled', 'Suspendu')], default='en_cours'),
        ),
    ]
