# Generated by Django 4.1.1 on 2022-10-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0003_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(0, 'en_cours'), (1, 'En ligne'), (2, 'Suspendu')], default=0),
        ),
    ]
