# Generated by Django 4.1.1 on 2022-10-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0004_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
