# Generated by Django 4.1.1 on 2022-10-15 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.IntegerField(choices=[(0, 'Web'), (1, 'Mobile'), (2, 'Desktop'), (3, 'Other')], default=0, max_length=50),
        ),
        migrations.CreateModel(
            name='DetailsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_project', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_test.project')),
            ],
            options={
                'verbose_name': 'DetailsProject',
                'verbose_name_plural': 'DetailsProjects',
            },
        ),
    ]
