# Generated by Django 4.1.1 on 2022-10-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0006_alter_project_category_detailsproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.IntegerField(choices=[(0, 'Web'), (1, 'Mobile'), (2, 'Desktop'), (3, 'Other')], default=0),
        ),
    ]
