# Generated by Django 4.1.1 on 2022-10-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0008_project_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_name',
            field=models.CharField(choices=[(0, 'Web'), (1, 'Mobile'), (2, 'Desktop'), (3, 'Other')], default='Web', max_length=20),
        ),
    ]
