# Generated by Django 4.1.1 on 2022-10-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0017_alter_project_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_name',
            field=models.CharField(choices=[('web', 'Site Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[('en_cours', 'en_cours'), (1, 'En ligne'), (2, 'Suspendu')], default=0),
        ),
    ]
