# Generated by Django 4.1.1 on 2022-10-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0018_alter_project_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('en_ligne', 'En ligne'), ('canceled', 'Suspendu')], default='en_cours', max_length=10),
        ),
    ]
