# Generated by Django 4.1.1 on 2022-10-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0019_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_name',
            field=models.CharField(choices=[('site_web', 'Site Web'), ('mobile', 'Mobile'), ('desktop', 'Desktop'), ('other', 'Other')], default='site_web', max_length=20),
        ),
    ]
