# Generated by Django 4.1.1 on 2022-10-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0022_alter_project_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_name',
            field=models.CharField(choices=[('site_web', 'Site Web'), ('appli_mobile', 'Appli Mobile'), ('appli_desktop', 'Appli Desktop'), ('other', 'Other')], default='site_web', max_length=20),
        ),
    ]
