# Generated by Django 4.1.1 on 2022-10-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0023_alter_project_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug_category', models.SlugField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
    ]
