# Generated by Django 4.1.1 on 2022-10-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0024_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
