# Generated by Django 4.1.1 on 2022-10-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0029_delete_tags_alter_project_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_name',
            field=models.CharField(choices=[('site_web', 'Site Web'), ('appli_mobile', 'Appli Mobile'), ('appli_desktop', 'Appli Desktop'), ('other', 'Other')], default=2, max_length=50),
        ),
    ]
