# Generated by Django 4.1.1 on 2022-10-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0036_alter_project_options_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project_category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
