# Generated by Django 4.1 on 2022-09-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_envoye',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'envoi"),
        ),
    ]
