# Generated by Django 4.1 on 2022-09-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
