# Generated by Django 4.1 on 2022-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_categories_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.IntegerField(choices=[(0, 'Développement'), (1, 'Programmation')], default=0, null=True),
        ),
    ]
