# Generated by Django 4.1 on 2022-09-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, choices=[(0, 'Développement'), (1, 'Programmation')], default=0, max_length=150, null=True),
        ),
    ]
