# Generated by Django 4.1.1 on 2022-09-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slugcat',
        ),
    ]
