# Generated by Django 4.1.1 on 2022-09-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_slug_category_slugcat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugcat',
            new_name='slug',
        ),
    ]
