# Generated by Django 4.1.1 on 2022-09-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_slugcat_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnails/default.png', upload_to='blog/thumbnails'),
        ),
    ]
