# Generated by Django 4.1.1 on 2022-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnails/default.png', upload_to='blog/thumbnails/'),
        ),
    ]
