# Generated by Django 4.1.3 on 2022-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnails/default.png', upload_to='images/portfolio/project/'),
        ),
    ]
