# Generated by Django 4.1.3 on 2022-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/blog/thumbnails/default.jpg', upload_to='images/blog/thumbnails/'),
        ),
    ]
