# Generated by Django 4.1.3 on 2022-11-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_category',
            field=models.ImageField(blank=True, default='images/blog/thumbnails/category/default.jpg', null=True, upload_to='images/blog/thumbnails/category/'),
        ),
    ]
