# Generated by Django 4.1.3 on 2022-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_category_img_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_category',
            field=models.ImageField(blank=True, default='images/blog/thumbnails/category/default.jpg', null=True, upload_to='images/blog/thumbnails/'),
        ),
    ]
