# Generated by Django 4.1.3 on 2022-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_category_img_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/blog/prod/default.png', upload_to='images/blog/prod/'),
        ),
    ]
