# Generated by Django 4.1.4 on 2022-12-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_content2_post_content3_post_content4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(null=True),
        ),
    ]
