# Generated by Django 4.1.4 on 2022-12-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_post_content_alter_post_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(default='vhjg'),
            preserve_default=False,
        ),
    ]
