# Generated by Django 4.1 on 2022-08-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=2500, null=True)),
                ('date_send', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-date_send'],
            },
        ),
    ]
