# Generated by Django 4.1 on 2022-09-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='subject',
        ),
    ]
