# Generated by Django 4.1.1 on 2022-10-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
