# Generated by Django 4.1 on 2022-09-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_email_contact_from_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='from_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='name',
        ),
    ]
