# Generated by Django 4.1.1 on 2022-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_from_email_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, max_length=120, null=True)),
                ('image_language', models.ImageField(blank=True, null=True, upload_to='portfolio/images/languages')),
            ],
            options={
                'ordering': ['language_name'],
            },
        ),
    ]
