# Generated by Django 4.1.1 on 2022-10-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectlist_project_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlist',
            options={'ordering': ['-project_date_created_on'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
