# Generated by Django 4.1.1 on 2022-10-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_category_projectlist_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='ProjectList',
        ),
    ]
