# Generated by Django 4.1.1 on 2022-10-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_language_delete_projectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug_project', models.SlugField(blank=True, max_length=120, null=True)),
                ('project_description', models.TextField(blank=True, max_length=2500, null=True)),
                ('project_image', models.ImageField(default='portfolio/images/default.png', upload_to='portfolio/images/')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('project_date', models.DateTimeField(auto_now=True, null=True)),
                ('project_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category')),
            ],
            options={
                'ordering': ['project_name'],
            },
        ),
    ]
