# Generated by Django 4.1.1 on 2022-10-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_options_project_choix_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
