# Generated by Django 4.1.1 on 2022-10-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_language_options_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['language_name']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language_name',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
