# Generated by Django 4.1.1 on 2022-10-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_project_project_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(blank=True, max_length=120, null=True)),
                ('category_name', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('image_cat', models.ImageField(default='images/portfolio/category/default.jpg', upload_to='images/portfolio/category')),
                ('description_cat', models.TextField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['project_category'],
            },
        ),
    ]
