# Generated by Django 4.1.1 on 2022-10-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='project_category',
        ),
    ]
