# Generated by Django 4.1.1 on 2022-10-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoiey',
        ),
        migrations.AlterModelOptions(
            name='categoiey',
            options={'ordering': ['category_name'], 'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
