# Generated by Django 4.1.1 on 2022-10-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_category_categoiey_alter_categoiey_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoiey',
            new_name='Categorie',
        ),
    ]
