# Generated by Django 4.1.1 on 2022-10-31 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_categoiey_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('date_created_on', models.DateTimeField(auto_now_add=True)),
                ('project_status', models.CharField(choices=[(1, 'En Cours'), (2, 'En ligne'), (3, 'Suspendu')], default=1, max_length=30)),
                ('project_thumbnail', models.ImageField(default='images/portfolio/project/default.jpg', upload_to='images/portfolio/project/')),
                ('project_url', models.URLField(default='https://antho635.github.io/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.categorie')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_created_on'],
            },
        ),
    ]
