# Generated by Django 4.1.1 on 2022-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('en_cours', 'En Cours'), (2, 'En ligne'), (3, 'Suspendu')], default='en_cours', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(default='antho635.github.io/'),
        ),
    ]
