# Generated by Django 4.1.3 on 2022-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_project_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('En Cours', 'En Cours'), ('En ligne', 'En ligne'), ('Suspendu', 'Suspendu')], default='en_cours', max_length=30),
        ),
    ]
