# Generated by Django 4.1.3 on 2022-11-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_project_project_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_projects', to='portfolio.categorie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(default='#'),
        ),
    ]
