# Generated by Django 4.1.3 on 2022-11-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_project_category_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(default='images/portfolio/project/default.jpg', upload_to='images/blog/thumbnails/'),
        ),
    ]
