# Generated by Django 4.1.3 on 2022-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_project_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image_cat',
            field=models.ImageField(default='images/portfolio/category/default.jpg', upload_to='images/blog/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(default='images/blog/thumbnails/default.png', upload_to='images/blog/thumbnails/'),
        ),
    ]
