# Generated by Django 4.1.3 on 2022-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_categorie_image_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image_cat',
            field=models.ImageField(default='images/portfolio/category/default.jpg', upload_to='images/portfolio/category/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(default='images/portfolio/project/default.png', upload_to='images/portfolio/project/'),
        ),
    ]
