# Generated by Django 4.1.3 on 2022-11-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_categorie_image_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image_cat',
            field=models.ImageField(default='images/blog/thumbnails/default.jpg', upload_to='images/blog/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.ImageField(default='images/blog/thumbnails/default.jpg', upload_to='images/blog/thumbnails/'),
        ),
    ]
